### ISSUE TITLE
isEqualTo() compares object references

### ISSUE THREAD

**Issue by malek-alseelawi** [vegegoku/induction-task#2]
https://github.com/vegegoku/induction-task/blob/63ff5a92d7ed9c36e3e529d36d5684b00abaf985/snack-machine/src/test/java/com/progressoft/induction/MoneyTest.java#L25

isnt this will always fail as isEqualTo() compares object references ??
i think it should be isEqualToComparingFieldByField()
am i right or i'm missing something !!

**Comment by vegegoku** [comment]
It is the job of the candidates to implement this in a way that make it work as is.
